theme: jekyll-theme-architect
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

title: Kickoman(us)
description: Check out this page and then just touch me
